export const DISCLAIMER_ES = "Los planes nutricionales generados por Paraguachi Meals Prep son de carácter orientativo y educativo. No constituyen consejo médico, diagnóstico ni tratamiento. No reemplazan la consulta con un médico, nutricionista o dietista certificado. Si padeces diabetes, hipertensión, enfermedad renal u otras condiciones médicas, consulta siempre a tu médico antes de realizar cambios en tu alimentación.";

export const DISCLAIMER_EN = "The nutritional plans generated by Paraguachi Meals Prep are for guidance and educational purposes only. They do not constitute medical advice, diagnosis, or treatment. They do not replace consultation with a physician, nutritionist, or certified dietitian. If you have diabetes, hypertension, kidney disease, or other medical conditions, always consult your doctor before making changes to your diet.";

export const DISCLAIMER_FOOTER_ES = "© Paraguachi Meals Prep · Ing. Chef Alexander Matute & Ing. Nelly Rendón, Especialista en Manipulación y Conservación de Alimentos · Los Angeles, CA · Basada en: ADA 2024, AHA 2024, DASH Diet Guidelines, ISSN Sport Nutrition";

export const DISCLAIMER_FOOTER_EN = "© Paraguachi Meals Prep · Chef Eng. Alexander Matute & Eng. Nelly Rendón, Food Handling & Preservation Specialist · Los Angeles, CA · Based on: ADA 2024, AHA 2024, DASH Diet Guidelines, ISSN Sport Nutrition";

export function getDisclaimer(lang: "es" | "en") {
  return lang === "es" ? DISCLAIMER_ES : DISCLAIMER_EN;
}
