
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS sexo text;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS edad integer;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS peso_kg numeric;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS altura_cm numeric;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS dias_ejercicio integer DEFAULT 0;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS tipo_ejercicio text;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS duracion_ejercicio text;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS nivel_experiencia text;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS horario_entreno text;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS fase_entrenamiento text;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS tipo_diabetes text;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS usa_insulina boolean DEFAULT false;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS hba1c numeric;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS enfermedad_renal boolean DEFAULT false;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS presion_sistolica integer;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS presion_diastolica integer;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS meta_sodio text DEFAULT 'estandar';
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS medicamentos text[] DEFAULT '{}';
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS horas_sueno integer DEFAULT 7;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS nivel_estres text DEFAULT 'medio';
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS grasa_corporal numeric;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS cintura_cm numeric;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS cadera_cm numeric;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS brazo_cm numeric;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS resistencia_insulina text;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS tmb numeric;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS tdee numeric;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS calorias_objetivo numeric;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS proteina_g numeric;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS carbos_g numeric;
ALTER TABLE public.preferencias ADD COLUMN IF NOT EXISTS grasas_g numeric;
